### PR TITLE
Enable Frozen String Literals

### PR DESCRIPTION
**Pull request by yob**
Add the `frozen_string_literal: true` pragma to all files in `lib`.

I'm yet to do any benchmarks, but this should reduce object allocations on ruby 2.3+, which may improve performance

### CODE REVIEW

**Comment by yob** [comment]
Here's a benchmark script that counts ruby objects allocated while extracting text from a 4 page PDF:

```ruby
require 'pdf/reader'
require 'allocation_tracer'
require 'pp'

ObjectSpace::AllocationTracer.setup(%i{type})

res = ObjectSpace::AllocationTracer.trace do
  PDF::Reader.open("spec/data/cairo-unicode.pdf") do |pdf|
    pdf.pages.each do |page|
      page.text
    end
  end
end

pp res
``` 

Comparing master to this branch shows a ~16% reduction in overall object allocations, and a 35% reduction in string allocations:

table

Here's the same data in chart form:

chart

**Comment by yob** [comment]
Tests are green and I like the shape of that graph :shipit:

**Comment by zenspider** [comment]
Just curious but does this actually affect GC in any measurable way? I'm currently poking at `prepare_regular_token` and saw all the recent `"".dup` changes.

**Comment by yob** [comment]
Good question, I didn't benchmark GC timing - I made am assumption that fewer objects will mean less GC pressure.

The `dup` calls aren't great, but adding them while enabling frozen literals was a nett win.

I haven't been a super active maintainer for 4-5 years, so I'm sure there's plenty of optimisations that could be made across the library. It was only recently that I dropped 1.8 support, and modern ruby is a different beast.

**Comment by zenspider** [comment]
Totally fair.

I'll continue the performance side of my conversation in a new ticket. I'll refer back to this issue.

**Pull request merged**
